version: '3.8'
services:
  deepseek:
    build: .
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /mnt/model-cache:/root/.cache/huggingface  # Changed this line
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

volumes:
  model-cache:
    driver: local