version: '3.8'
services:
  deepseek:
    build: .
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - huggingface_cache:/root/.cache/huggingface

volumes:
  huggingface_cache: